from pathlib import Path
from typing import Dict, List, Tuple

import joblib
import matplotlib.pyplot as plt

from detector_framework import config

# Constants
RESULTS_DIR_NAME = "detector_framework/adfa_replicate/results"
FIGURES_DIR_NAME = "data/figures"
PLOT_FILE_NAME = "adfa_replicate.pdf"

# Mapping between curve filename (stem) and plotting label
LABEL_MAP = {
    "adfa_data_curve": "ADFA Det. | ADFA Malware Actions vs. Benign",
    "individual_behavior_curve": "ADFA Det. | This Work Ransomware Actions vs. Benign",
    "exclude_encryption_curve": "ADFA Det. | Ransomware Lifecycles vs. Benign (Excluding Enc.)",
    "partial_encryption_curve": "ADFA Det. | Ransomware Lifecycles vs. Benign (Including Enc.)",
    "full_encryption_curve": "ADFA Det. | Ransomware Lifecycles vs. Benign (Only Enc.)",
    "lapd_encryption_only_curve": "Falcon    | Ransomware Lifecycles vs. Benign (Only Enc.)",
}

# Plotting parameters for each curve type
CURVE_PARAMS = {
    "adfa_data_curve": {"color": "darkorange", "linestyle": "--", "lw": 3},
    "individual_behavior_curve": {"color": "red", "linestyle": "--", "lw": 3},
    "exclude_encryption_curve": {"color": "green", "linestyle": "-"},
    "partial_encryption_curve": {"color": "blue", "linestyle": "-"},
    "full_encryption_curve": {"color": "purple", "linestyle": "-"},
    "lapd_encryption_only_curve": {"color": "black", "linestyle": ":", "lw": 3},
}


def load_curve_data(results_dir: Path) -> List[Tuple[Path, Tuple[List[float], List[float], float]]]:
    """
    Loads all curve files from the results directory and sorts them according to LABEL_MAP.
    """
    if not results_dir.exists():
        print(f"Warning: Results directory {results_dir} does not exist.")
        return []

    curve_files = list(results_dir.glob("*curve*.joblib"))
    
    # Sort curve_files to match the order in LABEL_MAP
    label_keys = list(LABEL_MAP.keys())
    curve_files.sort(key=lambda x: label_keys.index(x.stem) if x.stem in label_keys else len(label_keys))

    loaded_data = []
    for curve_file in curve_files:
        try:
            data = joblib.load(curve_file)
            loaded_data.append((curve_file, data))
        except Exception as e:
            print(f"Error loading {curve_file}: {e}")

    return loaded_data


def plot_roc_curves(loaded_data: List[Tuple[Path, Tuple[List[float], List[float], float]]]):
    """
    Generates the ROC curve plot from the loaded data.
    """
    fig = plt.figure(figsize=(8, 6))
    plt.rcParams['font.size'] = 18

    # Calculate max label length to avoid excessive spacing
    max_label_len = 0
    labels = []
    for curve_file, _ in loaded_data:
        label = LABEL_MAP.get(curve_file.stem, curve_file.stem.replace("_", " ").replace(" curve", ""))
        labels.append(label)
        if len(label) > max_label_len:
            max_label_len = len(label)

    for (curve_file, (fpr, tpr, auc)), label in zip(loaded_data, labels):
        # Get plotting parameters, fallback to defaults if not found
        params = CURVE_PARAMS.get(curve_file.stem, {"color": None, "linestyle": "-"})
        
        plt.plot(
            fpr, tpr, 
            lw=params.get("lw", 4),
            label=f"{label:<{max_label_len}}: {auc:.3f}",
            alpha=0.7, 
            color=params.get("color"),
            linestyle=params.get("linestyle")
        )

    # Plot diagonal reference line
    # plt.plot([0, 1], [0, 1], lw=2, color="black", alpha=0.5, linestyle='--')
    
    plt.xlim([-0.01, 1.01])
    plt.ylim([-0.01, 1.01])
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.legend(loc="lower center", bbox_to_anchor=(0.44, 1.05), ncol=1, prop={'family': 'monospace', 'size': 12})
    plt.tight_layout(rect=[0, 0, 1, 1.05])
    plt.grid(True)
    return fig


def plot_adfa_replicate(project_root: Path, show_plot: bool = False):
    """
    Refactored function to be called from plotting.py
    """
    results_dir = project_root / RESULTS_DIR_NAME
    figures_dir = project_root / FIGURES_DIR_NAME

    loaded_data = load_curve_data(results_dir)

    if not loaded_data:
        print("No ADFA data loaded. Skipping ADFA plotting.")
        return

    fig = plot_roc_curves(loaded_data)

    figures_dir.mkdir(parents=True, exist_ok=True)
    plot_path = figures_dir / PLOT_FILE_NAME
    plt.savefig(plot_path)
    print(f"ADFA Plot saved to {plot_path}")

    if show_plot:
        plt.show(block=True)
    
    plt.close(fig)


def main():
    """
    Main function to orchestrate loading data, plotting, and saving the figure.
    """
    # Data should first be generated by plotting.py (ADFA_GEN -> True), adfa.py, and adfa_new_data.py
    config.set_seed()
    project_root = Path(__file__).resolve().parent.parent.parent
    plot_adfa_replicate(project_root, show_plot=True)


if __name__ == "__main__":
    main()