version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  memcached:
    image: memcached
    ports:
      - "11211:11211"

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
      - memcached

volumes:
  pgdata:

